apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: statsd
  name: statsd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: statsd
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: statsd
    spec:
      containers:
      - image: graphiteapp/graphite-statsd
        imagePullPolicy: ""
        name: statsd
        ports:
        - containerPort: 80
        - containerPort: 2003
        - containerPort: 8125
        - containerPort: 8126
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
