apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: temporal
  name: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: temporal
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: temporal
    spec:
      containers:
      - env:
        - name: DB
          value: mysql
        - name: DYNAMIC_CONFIG_FILE_PATH
          value: config/dynamicconfig/development.yaml
        - name: MYSQL_PWD
          value: root
        - name: MYSQL_SEEDS
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: STATSD_ENDPOINT
          value: statsd:8125
        image: temporalio/auto-setup:0.20.0
        imagePullPolicy: ""
        name: temporal
        ports:
        - containerPort: 7233
        - containerPort: 7234
        - containerPort: 7235
        - containerPort: 7239
        - containerPort: 6933
        - containerPort: 6934
        - containerPort: 6935
        - containerPort: 6939
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
