apiVersion: v1
kind: Service
metadata:
  name: cadence-web-lb-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: cadence-web
spec:
  type: LoadBalancer
  selector:
    app: cadence-web
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 8088