apiVersion: v1
kind: Service
metadata:
  name: snap-temporal-server-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: snap-temporal
spec:
  type: LoadBalancer
  selector:
    app: snap-temporal
  ports:
    - protocol: TCP
      port: 7233
      targetPort: 7233