apiVersion: v1
kind: Service
metadata:
  name: temporal-nodeport
  labels:
    app: temporal
spec:
  type: NodePort
  selector:
    app: temporal
  ports:
    - protocol: TCP
      name: http2
      port: 7233